### ISSUE TITLE
Mismatch in factor levels in sparse_model_matrix

### ISSUE THREAD

**Issue by cmcclellan** [kylebutts/did2s#10]
In your sparse_model_matrix function the 'unlist(select)' vector of variable names can sometimes be different from the variable names in Z_fixef causing an error when you try to subset Z_fixef to the names in 'select'.  It seems this is being driven by differences in which factor level is dropped between Matrix::sparse.model.matrix(frmla, data = data) and fixest::fixef(fixest) in the second term of the fixed effect formula (e.g. year in ~0|state+year) .

If the input data are ordered by the second term, then both will drop the same level.  However, if the data are out of order, it looks like the Matrix::sparse.model.matrix drops the first level encountered while fixest somehow orders them first then drops the first level encountered.

The workaround is then to make sure your data is ordered by the subsequent terms in your fixed effect equation (although not sure if this generalizes further to three or more terms).

**Comment by kylebutts** [comment]
Hi @cmcclellan, are you using the dev version on github? I recently updated the sparse_model_matrix function, so I just want to make sure before diving into this issue.

**Comment by cmcclellan** [comment]
I'm using the CRAN version (0.4.0), mainly because I tried using the dev version first and wasn't getting any result from it (For replication, I was using the example/data on the github page).  I didn't dig too deep, but the problem there seemed to be in the calculation of the clustered standard errors.  If I recall, the meat/make_meat function was returning zero x zero matrices.  I didn't dig into it much more, but something is going on in the make_g function.

**Comment by kylebutts** [comment]
Yeah, the github version should fix those problems. I noticed these kind of issues and with the help of @lrberge, we rewrote it. If you could try again with the github version, that would be appreciated. It should definitely work as it passes all the tests.
