### ISSUE TITLE
Check Sun and Abraham code

### ISSUE THREAD

**Issue by kylebutts** [kylebutts/did2s#11]
A few people have found weird results, so I might be coding it up wrong in `event_study`

**Comment by TobiasMy** [comment]
Does the event study for Sun and Abraham behave correctly now? Running this code from the [documentation](https://kylebutts.com/did2s/reference/event_study.html) in the latest version (did2s_0.5.0) compiled from Github:

`
data(df_het, package = "did2s")
out = event_study(
  data = df_het, yname = "dep_var", idname = "unit",
  tname = "year", gname = "g"
)
plot_event_study(out)
`
Produces this result:

![did2s df_het event_study results](https://user-images.githubusercontent.com/102600536/160630149-345ffa8a-5e1f-4151-a2fb-333fd35097e4.png)

The Sun and Abraham facet indeed appears identical to the output from:

`
fixest_sunab <- feols(fml= dep_var ~ 1 + sunab(cohort=g, period=year, ref.c=0, ref.p=-1),
                      data=df_het)
iplot(fixest_sunab)
`
However, this seems to be very off compared to all other event studies. While the general direction here is still correct, in my personal application the direction of effect was reversed compared to all other event studie. I just want to make sure this is indeed the expected outcome and not a bug after the recent change.

**Comment by kylebutts** [comment]
Hi @TobiasMy, I'm not sure why it's so much noisier than the other estimators. Unless I'm mistaken, that's the proper syntax for `sunab`. I'm sorry I can't be of more help.

**Comment by TobiasMy** [comment]
Just one more note I forgot in my initial comment: The output included in the event_study [documentation](https://kylebutts.com/did2s/reference/event_study.html) (shown below) seemed to show a Sun and Abraham event study much more in line with all the rest which initially sparked my doubts.

![grafik](https://user-images.githubusercontent.com/102600536/160644719-af708ab5-f1a4-4c5c-a95e-93694a1d0810.png)

I wanted to thank you for this great package, it is of enormous help to me. Cheers!

**Comment by kylebutts** [comment]
@TobiasMy Okay, so I was doing the `sunab` code wrong *facepalm*

It should be all fixed now!

**Comment by TobiasMy** [comment]
Thanks a ton @kylebutts!  Seems like I fell into the same trap when trying to figure out how `sunab` worked from the vignette. I had just assumed that the fixed effects would automatically be taken care of and did not need to be specified extra. Adding such an FE example to the `sunab` vignette would certainly help prevent future users making this mistake. Thanks again for investigating this issue.

**Comment by kylebutts** [comment]
It's fixed in the documentation now: https://github.com/lrberge/fixest/issues/287
