### ISSUE TITLE
Error in select_obs(linear.mat, -obs2remove, nthreads) 

### ISSUE THREAD

**Issue by liqizheng0328** [kylebutts/did2s#21]
Running Two-stage Difference-in-Differences
• first stage formula `~ gdp_rete + open + ftri + fdi_share + rd_expenditure + rta + w_degree | country_hs_code + year`
• second stage formula `~ i(treat, ref = FALSE)`
• The indicator variable that denotes when treatment is on is `treat`
• Standard errors will be clustered by `iso3`
Error in fixest::feols(fixest::xpd(~0 + ..second_stage, lhs = yname),  : 
  Error in select_obs(linear.mat, -obs2remove, nthreads) : 
  After removing NAs (or perfect fit fixed-effects), not a single explanatory variable is different from 0.
This error was unforeseen by the author of the function feols. If you think your call to the function is legitimate, could you report?

**Comment by kylebutts** [comment]
You just posted your error message. A bit of politeness would be appreciated when asking for help. 

The error message is pretty clear on what's happening. There's an error in the `second_stage` regression. You can manually see what's going on by doing the following (assuming `dep_var` is the name of your y variable; change it to whatever it is):

```r
first_stage = feols(
  dep_var ~ gdp_rete + open + ftri + fdi_share + rd_expenditure + rta + w_degree | country_hs_code + year, 
  data = df[df$treat == 0, ]
)

df$dep_var_resid = df$dep_var - predict(first_stage, newdata = df)

second_stage = feols(
  dep_var_resid ~ i(treat, ref = FALSE), data = df
)
```

**Comment by liqizheng0328** [comment]
> You just posted your error message. A bit of politeness would be appreciated when asking for help.
> 
> The error message is pretty clear on what's happening. There's an error in the `second_stage` regression. You can manually see what's going on by doing the following (assuming `dep_var` is the name of your y variable; change it to whatever it is):
> 
> ```r
> first_stage = feols(
>   dep_var ~ gdp_rete + open + ftri + fdi_share + rd_expenditure + rta + w_degree | country_hs_code + year, 
>   data = df[df$treat == 0, ]
> )
> 
> df$dep_var_resid = df$dep_var - predict(first_stage, newdata = df)
> 
> second_stage = feols(
>   dep_var_resid ~ i(treat, ref = FALSE), data = df
> )
> ```

I apologize for not exhibiting enough politeness in my initial inquiry. Thank you for bringing this to my attention, and I will strive to improve my communication style.

Regarding the error message, I understand that there is an issue with the second-stage regression. Your suggestion was helpful, and I will try to manually inspect my dependent variable as you suggested. However, I have encountered challenges in processing my data due to a high amount of missing values( it appears when computing dep_var_resid). Do you have any suggestions or methods for handling missing values?

Thank you for your patient response.

**Comment by kylebutts** [comment]
Hi, I'm not sure without your data, but I would assume it's because some of your covariates are missing, which prevents `predict` from predicting for those rows in your dataset.
