### ISSUE TITLE
connecting did2s to honest did

### ISSUE THREAD

**Issue by Randol340** [kylebutts/did2s#22]
Dear authors, 
Thank you very much for writing the code and detailed documentation for the two-stage diff-in-diff! 
I have a question about connecting did2s to honest did. On this documentation of honest did https://github.com/asheshrambachan/HonestDiD, there is an example of transforming the Callaway and Santanna result and then apply to the honest did function. I wonder if (and how) we can use to results from diid2s in honest did? 
Thank you very much for your suggestion!

**Comment by kylebutts** [comment]
I'm not sure I understand what you want on `did2s`'s end. A `did2s` call returns a `fixest` object, you can follow the README and get `betahat` and `sigma` and use any function from `HonestDiD` as needed.

```r
library(fixest)
library(data.table)
library(did2s)
library(HonestDiD)

data(df_hom)
twfe_results <- did2s(df_hom,
  yname = "dep_var", treatment = "treat", cluster_var = "state",
  first_stage = ~ 0 | unit + year,
  second_stage = ~ i(rel_year, ref = c(-1, Inf))
)

betahat <- summary(twfe_results)$coefficients # save the coefficients
sigma <- summary(twfe_results)$cov.scaled # save the covariance matrix

HonestDiD::createSensitivityResults_relativeMagnitudes(
  betahat = betahat, # coefficients
  sigma = sigma, # covariance matrix
  numPrePeriods = 5, # num. of pre-treatment coefs
  numPostPeriods = 2, # num. of post-treatment coefs
  Mbarvec = seq(0.5, 2, by = 0.5) # values of Mbar
)

```

**Comment by Randol340** [comment]
Hi Kyle, thank you so much for your help!!

I encountered an error in running this line of code: I wonder if you have any ideas about how I can fix it?
`> event_time <- gsub("relquarter::", "", names(coef(twfe_results1))) |> as.numeric() # get event-time`
`Warning: NAs introduced by coercion`

The panel data is at quarter level and `relquarter` is the relative quarter to treatment with never treated coded as 999.

Thank you again!

**Comment by kylebutts** [comment]
I would need more information. Could you show me your `did2s` call?

**Comment by Randol340** [comment]
Thank you so much for your willingness to help!!

Here is the code I run for the `did2s`. `dat` is an unbalanced panel at `locid` `quarter` level.
```
dat = dat[!is.na(dat$treat_q),]
setDT(dat)
dat$relquarter[is.na(dat$relquarter)] = 999 
dat$quarter_added[is.na(dat$quarter_added)] = 0

# Gardner estimation 
twfe_results1 <- did2s(dat, 
               yname = "lntot_rec", first_stage = ~ 0 | locid + quarter, 
               second_stage = ~i(treat_q, ref=0), treatment = "treat_q", 
               cluster_var = "locid")

### Event Study w/ Gardner
es_sample1 <- did2s(dat, 
                yname = "lntot_rec", first_stage = ~ 0 | locid + quarter, 
                second_stage = ~i(relquarter, ref=c(-1, 999)), treatment = "treat_q", 
               cluster_var = "locid")

pdf(paste(sample,"_gardner.pdf", sep=""))

fixest::iplot(es_sample1, main = "", ylab="", xlab = "Quarters from add", col = "steelblue", ref.line = -1, xlim=c(-8,8),ylim=c(-0.1,0.15))
axis(side=1,at=(-8:8))

dev.off()
```

**Comment by kylebutts** [comment]
Hmmm, I'm not sure why that's erroring. What's the output of `names(coef(twfe_results1))`? All that `gsub` is doing is removing `relquarter::` from the coefficient names and then it converts the strings to numbers.

**Comment by kylebutts** [comment]
You don't need to drop -1 in the `ref` option. `second_stage = ~i(relquarter, ref=c(999))` should do the trick

**Comment by Randol340** [comment]
Thank you so much!

I encountered another problem when keep running the code: `beta <- es_sample1$att.egt[-referencePeriodIndex]` returns NULL as  
```
> es_sample1$att.egt
NULL
``` 
I'm not sure if the `att.egt` is specific to the example using CSDID? Should I change it to `beta <- es_sample1$coefficients[-referencePeriodIndex]`?

And when I running the if statement when I choose `type == "smoothness"`, I get the following error message:
```
} else if (type == "smoothness") {
  robust_ci <- createSensitivityResults(
    betahat = es_sample1$att.egt,
    sigma = V,
    numPrePeriods = npre,
    numPostPeriods = npost,
    method = method,
    l_vec = baseVec1,
    monotonicityDirection = monotonicityDirection,
    biasDirection = biasDirection,
    alpha = alpha,
    parallel = parallel
  )
}

Error in A_SD %*% prePeriod.coef : 
  requires numeric/complex matrix/vector arguments
```
if I change `betahat = es_sample1$coefficients` the error message shows `Error in { : task 1 failed - "attempt to apply non-function"`

Thank you again for your continuous help!!

**Comment by kylebutts** [comment]
Ooops, yeah you access the coefficients of a fixest object with `coef(es_sample1)`. You need to drop the base-period, so `coef(es_sample1)[-referencePeriodIndex]`

**Comment by Randol340** [comment]
Yes, I've changed this. I think the problem now is the last step when I run this 
```
robust_ci <- createSensitivityResults(
    betahat = beta,
    sigma = V,
    numPrePeriods = npre,
    numPostPeriods = npost,
    method = method,
    l_vec = baseVec1,
    monotonicityDirection = monotonicityDirection,
    biasDirection = biasDirection,
    alpha = alpha,
    parallel = parallel
  )
```
I got an error message `Error in { : task 1 failed - "attempt to apply non-function"`. I wonder if you have any ideas? Thank you very much!

<img width="604" alt="image" src="https://user-images.githubusercontent.com/78134871/224826691-b32f3a16-3a53-4287-a636-638e28c07b51.png">

**Comment by kylebutts** [comment]
I'm not sure. I'm not the author of that package and don't know how it works. Sorry!

**Comment by Randol340** [comment]
Got it, no worries! Thank you for your help throughout!!!
