### ISSUE TITLE
Error in running 2sdid

### ISSUE THREAD

**Issue by Randol340** [kylebutts/did2s#25]
Hi Kyle,

Hope you're all well and sorry for bothering you again!

I got an error message when running 2sdid for one subsample:
```
Running Two-stage Difference-in-Differences
• first stage formula `~ 0 | locid + county_quarter`
• second stage formula `~ i(treat_q, ref = 0)`
• The indicator variable that denotes when treatment is on is `treat_q`
• Standard errors will be clustered by `locid`
NOTE: The fixed-effects are not regular, they cannot be straightforwardly interpreted.

warning: solve(): system is singular; attempting approx solution
Error in make_V(x1, x10, x2) : solve(): solution not found
```

The NOTE and warning appear when I use country*quarter fixed effect instead of quarter fixed effect. For the majority of the subsamples, the result can be successfully computed after NOTE and warning. But for this subsample, it says a solution cannot be found. I wonder if you have any insights about it? Thank you very much!!

**Comment by kylebutts** [comment]
Hi @Randol340, I think there might be a problem with perfectly fitting a unit perhaps? I'm not entirely sure without the dataset though.

**Comment by Randol340** [comment]
Hi Kyle, thanks for your reply! I've shared with you the data and code via email! Thanks again!
