### ISSUE TITLE
did2s is dropping observations

### ISSUE THREAD

**Issue by michaeltopper1** [kylebutts/did2s#27]
Hi @kylebutts,

Not sure if you know what could be causing this, but I see some discrepancies in the number of observations that are being used to estimate my model.

It looks like when using `fixest::feols` I have no dropped observations. However, when I use `did2s`, I am getting a few observations dropped, and there is also no error message telling me of this.

I am wondering the following:

1. What could be causing this dropping of observations? I am attaching a screenshot (since reprex won't work for a huge dataset that I am using) of myself estimating

> 1) an OLS model with fixest (no dropped observations):
<img width="1044" alt="ols" src="https://github.com/kylebutts/did2s/assets/54960816/43a8ee79-df10-46e8-8f83-61d28360dc07">

> 2) a did2s of the same model (drops 32 observations)
<img width="956" alt="did2s" src="https://github.com/kylebutts/did2s/assets/54960816/168d4255-ff3f-4212-8649-a091157da720">

> 3) the first stage using fixest (no observations dropped) and the second stage (no observations dropped)
<img width="906" alt="stages" src="https://github.com/kylebutts/did2s/assets/54960816/74bf1a08-091e-4e3e-9af7-dee6e13d1a47">

2. Could an error message be made to indicate to the user when, and how many observations are dropped? 

Thanks for your help.

**Comment by kylebutts** [comment]
Hi Michael,

You're doing the first and second stage incorrectly. It should be:
```r
first_stage = feols(
  entry_to_dispatch ~ 0 | district + date + final_dispatch_description + hour, 
  data = dispatch_panel_p1[dispatch_panel_p1$treatment == 0, ]
)
dispatch_panel_p1$y_resid = dispatch_panel_p1$entry_to_dispatch - predict(first_stage, newdata = dispatch_panel_p1)
second_stage = feols(
  y_resid ~ i(treatment),
  data = dispatch_panel_p1
)
```

Almost surely the droped observations comes from not being able to `predict` some obs with `treatment == 1`.

**Comment by michaeltopper1** [comment]
Yikes, an embarassing error on my part. Sorry about that.

You are correct, the second stage is now dropping the observations.

However, I do think that an error message for observations dropped could be helpful for users. This is not an urgent issue by any means, but it could be a good enhancement down the line.

Thanks for the help!

Michael
