### ISSUE TITLE
Computational error with many fixed effects

### ISSUE THREAD

**Issue by beaubressler** [kylebutts/did2s#29]
Hello!

I get an error when running this code with an additional set of fixed effects: 
es <- did2s(event_study_data_basic_did2s,
            yname = "blck_sh", first_stage = ~ 0 | year + treated_id + TRACTA, 
            second_stage = ~i(event_time, ref=c(-1, Inf)), treatment = "treated", 
            cluster_var = "treated_id")

The error I get is:
Error in .local(x, ...) : 
  cs_lu(A) failed: near-singular A (or out of memory)

I don't get an error if I run the first stage with either "year + treated_id" alone or "year + treated_id + TRACTA" alone. 

It's hard for me to interpret the error to know exactly why this might be (other than a memory issue under the hood). I am able to estimate the event study with all 3 fixed effects in standard feols. There are 332 treated_ids, and about 2000 TRACTA, so it ends up being a lot of fixed effects. event_study_data_basic_did2s has 150,000 observations.

If I run this with far fewer observations (e.g. 5000), it is able to run: 
es <- did2s(event_study_data_basic_did2s %>% filter(row_number() <= 5000),
            yname = "blck_sh", first_stage = ~ 0 | year + treated_id + TRACTA, 
            second_stage = ~i(event_time, ref=c(-1, Inf)), treatment = "treated", 
            cluster_var = "treated_id")

But if I run things with 10,000 observations, I get a new error: 
"Error in .solve.dgC.sparse.lu(.sparse2g(a), b) : 
  A = LU is computationally singular: min(d)/max(d) = 1.045e-17, d = abs(diag(U))"

**Comment by kylebutts** [comment]
This is an error with calculating standard errors. You can use bootstrap options as an alternative to analytic standard errors

**Comment by beaubressler** [comment]
Ah right, thanks very much!
