### ISSUE TITLE
Can't find `honest_did_did2s` function with did2s version 1.1.0 installed & latest version of R

### ISSUE THREAD

**Issue by asmithh** [kylebutts/did2s#34]
Hi Kyle,
I have an M1 Mac running R 4.4.1 (the latest version for the ARM architecture). I'm having trouble getting R to find the `honest_did_did2s` function at the moment.

This is the output of sessionInfo():
```
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] HonestDiD_0.2.6   did2s_1.1.0       fixest_0.12.1     data.table_1.15.4
```

When I run this code, borrowed from the vignette, I get an error:
```
> sensitivity_results <- static0 |>
+   get_honestdid_obj_did2s(coef_name = "ts") |>
+   honest_did_did2s(
+     e = 0,
+     type = "relative_magnitude",
+     Mbarvec = seq(from = 0.5, to = 2, by = 0.5)
+   )
Error in honest_did_did2s(get_honestdid_obj_did2s(static0, coef_name = "ts"),  : 
  could not find function "honest_did_did2s"
 ```
 
 I'm not sure what's going wrong, but it seems like there's an issue importing the new functions, at least on Mac, perhaps?
Thank you!

**Comment by kylebutts** [comment]
@asmithh, for now that function only exists in the github version, you can run `devtools::install_github("kylebutts/did2s")` and it should be there. It just so happens that honestdid is on CRAN now, so this change in did2s should be up on CRAN soon

**Comment by asmithh** [comment]
Hi Kyle, thanks for your quick reply! Sorry I didn't mention it in my post, but I did install `did2s` through devtools using that command. I uninstalled & reinstalled (using the devtools command) with the same results, unfortunately.

**Comment by kylebutts** [comment]
Hi, could you tell me what outputs when you type `did2s:::honest_did_did2s`?

**Comment by kylebutts** [comment]
Hmm, I can't seem to reproduce this; not sure how to help. Are you sure you're doing `install_github()` and not `install()`? In the meanwhile, you could just copy the honest_did.R file and source it at the start of your script?

**Comment by asmithh** [comment]
I ended up absolutely nuking my R installation and reinstalling everything from scratch, then restarting my machine. I did reinstall R relatively recently, which is why I thought it wasn't necessary initially, but the nuclear option seemed to solve my problems. Sorry for taking up your time, and thank you for your help!

**Comment by kylebutts** [comment]
No problem; glad it's fixed!
