### ISSUE TITLE
staggered to remotes imports

### ISSUE THREAD

**Issue by grantmcdermott** [kylebutts/did2s#4]
Just a heads up that I just encountered a build error b/c the **staggered** package has been added to imports and it's not on CRAN. I'll push a [fix](https://remotes.r-lib.org/articles/dependencies.html#github-1) now.

Quasi-related. I think fixest should depend on version >0.9.0 b/c of the breaking changes to `i()`.

**Comment by kylebutts** [comment]
Ahh, yeah I was wondering how to do github only packages. Thanks! I agree about fixest

**Comment by grantmcdermott** [comment]
Do you want me to move it to Depends while I'm at it?
