### ISSUE TITLE
[bug] CS estimator and broom

### ISSUE THREAD

**Issue by filipemsc** [kylebutts/did2s#6]
I'm trying to run the `event_study` function and I'm obtaining the following error:

```
out = did2s::event_study(data_, "dep_var", "unit", "g", "year")
...
Estimating using Callaway and Sant'Anna (2020)
Error : No tidy method for objects of class AGGTEobj
``` 
I also tried to run using the source code and indeed it seems that `broom` package does not support Callaway and Sant'anna output

**Comment by grantmcdermott** [comment]
Have you loaded the **did** and **broom** packages? I think the latter might be unnecessary b/c did exports it's own `tidy()` method. But worth trying both..

**Comment by kylebutts** [comment]
I’ve gotten this a few times. Just update to the github version of did and it should work :-)

**Comment by grantmcdermott** [comment]
@kylebutts Maybe worth switching it to a remotes dependency in the DESCRIPTION file?

**Comment by filipemsc** [comment]
> 
> 
> I’ve gotten this a few times. Just update to the github version of did and it should work :-)

It worked! Thanks :)
